# Generated by Django 5.1.3 on 2025-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimesheet',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='employeeID',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
