# Generated by Django 5.1.3 on 2025-02-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_remove_employeetimesheet_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimesheet',
            name='employeeID',
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='employee',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
