# Generated by Django 5.1.3 on 2025-02-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_remove_employeetimesheet_employeeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetimesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
