# Generated by Django 5.1.3 on 2025-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_alter_employeetimesheet_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default=False, max_length=120),
        ),
    ]
