# Generated by Django 5.1.3 on 2025-03-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_alter_employeetimesheet_hours_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimesheet',
            name='hours_worked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
