# Generated by Django 5.1.3 on 2025-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_employeetimesheet_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_faces/'),
        ),
    ]
